/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Contrato;
import servicios.BajaServicio;
import servicios.ContratoServicio;
import servicios.Globales;
import static servicios.Globales.comportamientoTextField;
import servicios.NTPTimeService;

/**
 *
 * @author Nelkha
 */
public class ContAct extends javax.swing.JPanel {

    BajaServicio bajaServ = new BajaServicio();
    ContratoServicio contServ = new ContratoServicio();
    Contrato contrato;
   

    public ContAct() {
        initComponents();
        txtNombre.setEditable(false);
        txtDireccion.setEditable(false);
        txtFInicio.setEditable(false);
        txtFFin.setEditable(false);
        lblAlta.setVisible(false);
        lblBaja.setVisible(false);
        comportamientoTextField(txtIdCont, "ID CONTRATO");
        Globales.activarBuscarConEnter(txtIdCont, btnBuscar);
        btnConfirmar.setEnabled(false);
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        sepNombre = new javax.swing.JSeparator();
        sepDireccion = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtIdCont = new javax.swing.JTextField();
        sepFInicio = new javax.swing.JSeparator();
        txtFInicio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        txtFFin = new javax.swing.JTextField();
        sepFFin = new javax.swing.JSeparator();
        lblAlta = new javax.swing.JLabel();
        lblMensajeBajas = new javax.swing.JLabel();
        lblBaja = new javax.swing.JLabel();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sepNombre.setBackground(new java.awt.Color(255, 255, 255));
        sepNombre.setForeground(new java.awt.Color(0, 0, 0));
        sepNombre.setToolTipText("");
        sepNombre.setDoubleBuffered(true);
        sepNombre.setMinimumSize(new java.awt.Dimension(10, 10));
        sepNombre.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        sepDireccion.setBackground(new java.awt.Color(255, 255, 255));
        sepDireccion.setForeground(new java.awt.Color(0, 0, 0));
        add(sepDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 440, 20));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Inquilino");
        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion.setText("Inmueble");
        txtDireccion.setBorder(null);
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccionMouseClicked(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        btnConfirmar.setBackground(new java.awt.Color(0, 51, 153));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("DAR DE BAJA");
        btnConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE ID CONTRATO PARA BAJA ANTICIPADA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtIdCont.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCont.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdCont.setForeground(new java.awt.Color(102, 102, 102));
        txtIdCont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCont.setText("ID CONTRATO");
        txtIdCont.setBorder(null);
        txtIdCont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdContFocusLost(evt);
            }
        });
        txtIdCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdContMouseClicked(evt);
            }
        });
        txtIdCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContActionPerformed(evt);
            }
        });
        add(txtIdCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        sepFInicio.setBackground(new java.awt.Color(255, 255, 255));
        sepFInicio.setForeground(new java.awt.Color(0, 0, 0));
        sepFInicio.setToolTipText("");
        sepFInicio.setDoubleBuffered(true);
        sepFInicio.setMinimumSize(new java.awt.Dimension(10, 10));
        sepFInicio.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepFInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));

        txtFInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtFInicio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFInicio.setForeground(new java.awt.Color(102, 102, 102));
        txtFInicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFInicio.setText("Fecha inicio");
        txtFInicio.setBorder(null);
        txtFInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFInicioFocusLost(evt);
            }
        });
        txtFInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFInicioMouseClicked(evt);
            }
        });
        txtFInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFInicioActionPerformed(evt);
            }
        });
        add(txtFInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        txtFFin.setBackground(new java.awt.Color(255, 255, 255));
        txtFFin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtFFin.setForeground(new java.awt.Color(102, 102, 102));
        txtFFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFFin.setText("Fecha fin");
        txtFFin.setBorder(null);
        txtFFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFFinFocusLost(evt);
            }
        });
        txtFFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFFinMouseClicked(evt);
            }
        });
        txtFFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFFinActionPerformed(evt);
            }
        });
        add(txtFFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));

        sepFFin.setBackground(new java.awt.Color(255, 255, 255));
        sepFFin.setForeground(new java.awt.Color(0, 0, 0));
        sepFFin.setToolTipText("");
        sepFFin.setDoubleBuffered(true);
        sepFFin.setMinimumSize(new java.awt.Dimension(10, 10));
        sepFFin.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepFFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 20));

        lblAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/comprobado.png"))); // NOI18N
        add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        lblMensajeBajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblMensajeBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 290, 30));

        lblBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/cancelar.png"))); // NOI18N
        add(lblBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        contrato.setAlta(false);
        lblMensajeBajas.setText("Ya no esta vigente");
       
        try {
            contServ.editarContrato(contrato);
            lblAlta.setVisible(false);
            lblBaja.setVisible(true);
            lblMensaje.setText("El contrato fue dado de baja correctamente");
            btnConfirmar.setEnabled(false);
            

        } catch (Exception ex) {
            Logger.getLogger(ContAct.class.getName()).log(Level.SEVERE, null, ex);
            lblMensaje.setText("Algo fallo. El contrato no fue dado de baja");

        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtIdContFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdContFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContFocusLost

    private void txtIdContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdContMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContMouseClicked

    private void txtIdContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            long idContrato = Long.parseLong(txtIdCont.getText());

            contrato = contServ.buscarContratoPorId(idContrato);

            if (contrato != null) {
                txtNombre.setText(contrato.getInquilino().getNombre() + " " + contrato.getInquilino().getApellido());
                txtDireccion.setText(contrato.getInmueble().getDireccion());
                txtFInicio.setText(contrato.getFechaInicio().toString());
                txtFFin.setText(contrato.getFechaFin().toString());
                if (contrato.isAlta()) {
                    lblAlta.setVisible(true);
                    lblMensajeBajas.setText("El contrato esta vigente.");
                    lblMensaje.setText("¡¡¡ADVERTENCIA!!! Al dar la baja no podra volver a su estado anterior");
                    btnConfirmar.setEnabled(true);
                } else {
                    lblBaja.setVisible(true);
                    lblMensajeBajas.setText("El contrato ya no esta vigente.");
                    lblMensaje.setText("No se puede realizar ninguna accion ya que el contrato no esta vigente");

                }

            } else {
                lblMensaje.setText("No se ha encontrado ningún contrato con ese ID en la base de datos");
                txtNombre.setText("Inquilino");
                txtDireccion.setText("Inmueble");
                txtFInicio.setText("Fecha Inicio");
                txtFFin.setText("Fecha Fin");
            }
        } catch (NumberFormatException e) {
            lblMensaje.setText("El ID ingresado no es válido. Por favor, ingrese un número.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseClicked

    }//GEN-LAST:event_txtDireccionMouseClicked

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost

    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked

    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost

    }//GEN-LAST:event_txtNombreFocusLost

    private void txtFInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFInicioActionPerformed

    private void txtFInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFInicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFInicioMouseClicked

    private void txtFInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFInicioFocusLost

    }//GEN-LAST:event_txtFInicioFocusLost

    private void txtFFinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFFinFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFinFocusLost

    private void txtFFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFFinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFinMouseClicked

    private void txtFFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensajeBajas;
    private javax.swing.JSeparator sepDireccion;
    private javax.swing.JSeparator sepFFin;
    private javax.swing.JSeparator sepFInicio;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFFin;
    private javax.swing.JTextField txtFInicio;
    private javax.swing.JTextField txtIdCont;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
