/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import models.Contrato;
import servicios.BajaServicio;
import servicios.ContratoServicio;
import servicios.Globales;
import static servicios.Globales.comportamientoTextField;

/**
 *
 * @author Nelkha
 */
public class ContAct extends javax.swing.JPanel {

    BajaServicio bajaServ = new BajaServicio();
    ContratoServicio contServ = new ContratoServicio();
    Contrato contrato;
   

    public ContAct() {
        initComponents();
       
        txtDireccion.setEditable(false);
        
        comportamientoTextField(txtIdCont, "ID CONTRATO");
        Globales.activarBuscarConEnter(txtIdCont, btnBuscar);
        btnConfirmar.setEnabled(false);
       
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        sepDireccion = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtIdCont = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        sepNombre1 = new javax.swing.JSeparator();
        txtNombre2 = new javax.swing.JTextField();
        lblMensajeBajas1 = new javax.swing.JLabel();
        lblNuevaAltura = new javax.swing.JLabel();
        sepDireccion2 = new javax.swing.JSeparator();
        txtDireccion2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNuevaAltura1 = new javax.swing.JTextField();
        sepNuevaAltura1 = new javax.swing.JSeparator();
        lblTabAltura1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sepDireccion.setBackground(new java.awt.Color(255, 255, 255));
        sepDireccion.setForeground(new java.awt.Color(0, 0, 0));
        add(sepDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 440, 20));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion.setText("Inmueble");
        txtDireccion.setBorder(null);
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccionMouseClicked(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        btnConfirmar.setBackground(new java.awt.Color(0, 51, 153));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("ACTUALIZAR");
        btnConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE ID CONTRATO A ACTUALIZAR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtIdCont.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCont.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdCont.setForeground(new java.awt.Color(102, 102, 102));
        txtIdCont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCont.setText("ID CONTRATO");
        txtIdCont.setBorder(null);
        txtIdCont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdContFocusLost(evt);
            }
        });
        txtIdCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdContMouseClicked(evt);
            }
        });
        txtIdCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContActionPerformed(evt);
            }
        });
        add(txtIdCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        sepNombre1.setBackground(new java.awt.Color(255, 255, 255));
        sepNombre1.setForeground(new java.awt.Color(0, 0, 0));
        sepNombre1.setToolTipText("");
        sepNombre1.setDoubleBuffered(true);
        sepNombre1.setMinimumSize(new java.awt.Dimension(10, 10));
        sepNombre1.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        txtNombre2.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre2.setText("Inquilino");
        txtNombre2.setBorder(null);
        txtNombre2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombre2FocusLost(evt);
            }
        });
        txtNombre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombre2MouseClicked(evt);
            }
        });
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });
        add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        lblMensajeBajas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblMensajeBajas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 460, 30));

        lblNuevaAltura.setText("Ingrese nuevo importe");
        add(lblNuevaAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        sepDireccion2.setBackground(new java.awt.Color(255, 255, 255));
        sepDireccion2.setForeground(new java.awt.Color(0, 0, 0));
        add(sepDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));

        txtDireccion2.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDireccion2.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion2.setText("Precio");
        txtDireccion2.setBorder(null);
        txtDireccion2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccion2FocusLost(evt);
            }
        });
        txtDireccion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccion2MouseClicked(evt);
            }
        });
        txtDireccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccion2ActionPerformed(evt);
            }
        });
        add(txtDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 30, -1));

        txtNuevaAltura1.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevaAltura1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNuevaAltura1.setForeground(new java.awt.Color(102, 102, 102));
        txtNuevaAltura1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNuevaAltura1.setBorder(null);
        txtNuevaAltura1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevaAltura1FocusLost(evt);
            }
        });
        txtNuevaAltura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNuevaAltura1MouseClicked(evt);
            }
        });
        txtNuevaAltura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaAltura1ActionPerformed(evt);
            }
        });
        add(txtNuevaAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 130, 30));

        sepNuevaAltura1.setBackground(new java.awt.Color(255, 255, 255));
        sepNuevaAltura1.setForeground(new java.awt.Color(102, 204, 255));
        add(sepNuevaAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 20));

        lblTabAltura1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTabAltura1.setForeground(new java.awt.Color(102, 204, 255));
        lblTabAltura1.setText("TAB para confirmar");
        add(lblTabAltura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 230, 110));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Incrementos anteriores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        contrato.setAlta(false);
        
       
        try {
            contServ.editarContrato(contrato);
            
            lblMensaje.setText("El contrato fue dado de baja correctamente");
            btnConfirmar.setEnabled(false);
            

        } catch (Exception ex) {
            Logger.getLogger(ContAct.class.getName()).log(Level.SEVERE, null, ex);
            lblMensaje.setText("Algo fallo. El contrato no fue dado de baja");

        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtIdContFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdContFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContFocusLost

    private void txtIdContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdContMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContMouseClicked

    private void txtIdContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            long idContrato = Long.parseLong(txtIdCont.getText());

            contrato = contServ.buscarContratoPorId(idContrato);

            if (contrato != null) {
                txtDireccion.setText(contrato.getInmueble().getDireccion());
                if (contrato.isAlta()) {
                    lblMensaje.setText("¡¡¡ADVERTENCIA!!! Al dar la baja no podra volver a su estado anterior");
                    btnConfirmar.setEnabled(true);
                } else {
                    lblMensaje.setText("No se puede realizar ninguna accion ya que el contrato no esta vigente");

                }

            } else {
                lblMensaje.setText("No se ha encontrado ningún contrato con ese ID en la base de datos");
                txtDireccion.setText("Inmueble");
            }
        } catch (NumberFormatException e) {
            lblMensaje.setText("El ID ingresado no es válido. Por favor, ingrese un número.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseClicked

    }//GEN-LAST:event_txtDireccionMouseClicked

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost

    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtNombre2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2FocusLost

    private void txtNombre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombre2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2MouseClicked

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void txtDireccion2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccion2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion2FocusLost

    private void txtDireccion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion2MouseClicked

    private void txtDireccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion2ActionPerformed

    private void txtNuevaAltura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaAltura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaAltura1ActionPerformed

    private void txtNuevaAltura1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevaAltura1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaAltura1MouseClicked

    private void txtNuevaAltura1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevaAltura1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaAltura1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensajeBajas1;
    private javax.swing.JLabel lblNuevaAltura;
    private javax.swing.JLabel lblTabAltura1;
    private javax.swing.JSeparator sepDireccion;
    private javax.swing.JSeparator sepDireccion2;
    private javax.swing.JSeparator sepNombre1;
    private javax.swing.JSeparator sepNuevaAltura1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtIdCont;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNuevaAltura1;
    // End of variables declaration//GEN-END:variables
}
