/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Contrato;
import servicios.ContratoServicio;

/**
 *
 * @author Nelkha
 */
public class ContrList extends javax.swing.JPanel {

    ContratoServicio contServ = new ContratoServicio();
    DefaultTableModel dtm = new DefaultTableModel();
    List<Contrato> contratos = contServ.consultaTodos();

    public ContrList() {
        initComponents();
        String[] titulos = new String[]{"C. ID", "INQUILINO", "INMUEBLE", "INDEX"};
        dtm.setColumnIdentifiers(titulos);

        tblCont.setModel(dtm);
        tblCont.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblCont.getColumnModel().getColumn(1).setPreferredWidth(125);
        tblCont.getColumnModel().getColumn(2).setPreferredWidth(125);
        tblCont.getColumnModel().getColumn(3).setPreferredWidth(5);
        for (Contrato cont : contratos) {
            dtm.addRow(new Object[]{cont.getId(), cont.getInquilino().getNombre() + " " + cont.getInquilino().getApellido(), cont.getInmueble().getDireccion(),
                cont.getIndexacionMeses()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPI = new javax.swing.JPanel();
        btnNoVig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCont = new javax.swing.JTable();
        btnVig = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPI.setBackground(new java.awt.Color(255, 255, 255));
        contentPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNoVig.setBackground(new java.awt.Color(0, 51, 153));
        btnNoVig.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnNoVig.setForeground(new java.awt.Color(255, 255, 255));
        btnNoVig.setText("NO VIGENTES");
        btnNoVig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNoVig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNoVig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoVigActionPerformed(evt);
            }
        });
        contentPI.add(btnNoVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 130, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO DE CONTRATOS");
        contentPI.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        tblCont.setBackground(new java.awt.Color(255, 255, 255));
        tblCont.setForeground(new java.awt.Color(0, 0, 0));
        tblCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCont);

        contentPI.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, 360));

        btnVig.setBackground(new java.awt.Color(0, 51, 153));
        btnVig.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnVig.setForeground(new java.awt.Color(255, 255, 255));
        btnVig.setText("VIGENTES");
        btnVig.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVigActionPerformed(evt);
            }
        });
        contentPI.add(btnVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, 40));

        btnAll.setBackground(new java.awt.Color(0, 51, 153));
        btnAll.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnAll.setForeground(new java.awt.Color(255, 255, 255));
        btnAll.setText("TODOS");
        btnAll.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        contentPI.add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 40));

        add(contentPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoVigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoVigActionPerformed
dtm.setRowCount(0);
        for (Contrato cont : contratos) {
            if(!cont.isAlta()){
                dtm.addRow(new Object[]{cont.getId(), cont.getInquilino().getNombre() + " " + cont.getInquilino().getApellido(), cont.getInmueble().getDireccion(),
                cont.getIndexacionMeses()});
            }
            
        }       
    }//GEN-LAST:event_btnNoVigActionPerformed

    private void btnVigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVigActionPerformed
        dtm.setRowCount(0);
        for (Contrato cont : contratos) {
            if(cont.isAlta()){
                dtm.addRow(new Object[]{cont.getId(), cont.getInquilino().getNombre() + " " + cont.getInquilino().getApellido(), cont.getInmueble().getDireccion(),
                cont.getIndexacionMeses()});
            }
            
        }       
    }//GEN-LAST:event_btnVigActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        dtm.setRowCount(0);
        for (Contrato cont : contratos) {
            
            dtm.addRow(new Object[]{cont.getId(), cont.getInquilino().getNombre() + " " + cont.getInquilino().getApellido(), cont.getInmueble().getDireccion(),
                cont.getIndexacionMeses()});
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnNoVig;
    private javax.swing.JButton btnVig;
    private javax.swing.JPanel contentPI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCont;
    // End of variables declaration//GEN-END:variables
}
