/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Contrato;
import servicios.ContratoServicio;
import servicios.Globales;
import static servicios.Globales.comportamientoTextField;

/**
 *
 * @author Nelkha
 */
public class ContAct extends javax.swing.JPanel {

    ContratoServicio contServ = new ContratoServicio();
    Contrato contrato;

    public void actualizarUI() {
        boolean manual = rManual.isSelected();
        boolean porcentual = rPorcentual.isSelected();

        if (manual) {
            lblImporteManual.setVisible(true);
            lblPorc.setVisible(false);
        } else if (porcentual) {
            lblImporteManual.setVisible(false);
            lblPorc.setVisible(true);
        }

    }

    public ContAct() {
        initComponents();
        txtDireccion.setEditable(false);
        txtNombre.setEditable(false);
        txtPrecio.setEditable(false);
        rManual.setVisible(false);
        rPorcentual.setVisible(false);
        txtNuevoPrecio.setVisible(false);
        sepNuevoPrecio.setVisible(false);
        lblTabPrecio.setVisible(false);
        lblImporteManual.setVisible(false);
        lblPorc.setVisible(false);
        txtAAnt.setEditable(false);
        lblEditar.setVisible(false);
        comportamientoTextField(txtIdCont, "ID CONTRATO");
        Globales.activarBuscarConEnter(txtIdCont, btnBuscar);
        btnActualizar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        sepDireccion = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtIdCont = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        sepNombre1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblPorc = new javax.swing.JLabel();
        sepDireccion2 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        lblEditar = new javax.swing.JLabel();
        txtNuevoPrecio = new javax.swing.JTextField();
        sepNuevoPrecio = new javax.swing.JSeparator();
        lblTabPrecio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rManual = new javax.swing.JRadioButton();
        rPorcentual = new javax.swing.JRadioButton();
        lblImporteManual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAAnt = new javax.swing.JTextArea();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sepDireccion.setBackground(new java.awt.Color(255, 255, 255));
        sepDireccion.setForeground(new java.awt.Color(0, 0, 0));
        add(sepDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 440, 20));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion.setText("Inmueble");
        txtDireccion.setBorder(null);
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDireccionMouseClicked(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, 30));

        btnActualizar.setBackground(new java.awt.Color(0, 51, 153));
        btnActualizar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE ID CONTRATO A ACTUALIZAR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtIdCont.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCont.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdCont.setForeground(new java.awt.Color(102, 102, 102));
        txtIdCont.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCont.setText("ID CONTRATO");
        txtIdCont.setBorder(null);
        txtIdCont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdContFocusLost(evt);
            }
        });
        txtIdCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdContMouseClicked(evt);
            }
        });
        txtIdCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContActionPerformed(evt);
            }
        });
        add(txtIdCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        sepNombre1.setBackground(new java.awt.Color(255, 255, 255));
        sepNombre1.setForeground(new java.awt.Color(0, 0, 0));
        sepNombre1.setToolTipText("");
        sepNombre1.setDoubleBuffered(true);
        sepNombre1.setMinimumSize(new java.awt.Dimension(10, 10));
        sepNombre1.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Inquilino");
        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        lblPorc.setText("Ingrese % de incremento");
        add(lblPorc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        sepDireccion2.setBackground(new java.awt.Color(255, 255, 255));
        sepDireccion2.setForeground(new java.awt.Color(0, 0, 0));
        add(sepDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 130, 20));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPrecio.setText("Precio");
        txtPrecio.setBorder(null);
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrecioMouseClicked(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 110, 30));

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        lblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });
        add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 30, -1));

        txtNuevoPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevoPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNuevoPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtNuevoPrecio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNuevoPrecio.setBorder(null);
        txtNuevoPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevoPrecioFocusLost(evt);
            }
        });
        txtNuevoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNuevoPrecioMouseClicked(evt);
            }
        });
        txtNuevoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoPrecioActionPerformed(evt);
            }
        });
        add(txtNuevoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, 20));

        sepNuevoPrecio.setBackground(new java.awt.Color(255, 255, 255));
        sepNuevoPrecio.setForeground(new java.awt.Color(102, 204, 255));
        add(sepNuevoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, 20));

        lblTabPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTabPrecio.setForeground(new java.awt.Color(102, 204, 255));
        lblTabPrecio.setText("TAB para confirmar");
        add(lblTabPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Incrementos anteriores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        rManual.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rManual);
        rManual.setForeground(new java.awt.Color(51, 51, 51));
        rManual.setSelected(true);
        rManual.setText("Importe manual");
        rManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rManualActionPerformed(evt);
            }
        });
        add(rManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        rPorcentual.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rPorcentual);
        rPorcentual.setForeground(new java.awt.Color(51, 51, 51));
        rPorcentual.setText("Porcentual %");
        rPorcentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPorcentualActionPerformed(evt);
            }
        });
        add(rPorcentual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblImporteManual.setText("Ingrese nuevo importe(Manual)");
        add(lblImporteManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        txtAAnt.setColumns(20);
        txtAAnt.setRows(5);
        txtAAnt.setText("AQUI SE MOSTRARA LA PROGRESION DE PRECIOS.");
        jScrollPane1.setViewportView(txtAAnt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 300, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        contrato.setAlta(false);

        try {
            contServ.editarContrato(contrato);

            lblMensaje.setText("El contrato fue dado de baja correctamente");
            btnActualizar.setEnabled(false);

        } catch (Exception ex) {
            Logger.getLogger(ContAct.class.getName()).log(Level.SEVERE, null, ex);
            lblMensaje.setText("Algo fallo. El contrato no fue dado de baja");

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIdContFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdContFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContFocusLost

    private void txtIdContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdContMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContMouseClicked

    private void txtIdContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdContActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            long idContrato = Long.parseLong(txtIdCont.getText());

            contrato = contServ.buscarContratoPorId(idContrato);

            if (contrato != null) {
                txtNombre.setText(contrato.getInquilino().getNombre() + " " + contrato.getInquilino().getApellido());
                txtPrecio.setText("$" + contrato.getMontoAlquiler());
                txtDireccion.setText(contrato.getInmueble().getDireccion());
                StringBuilder incrementosText = new StringBuilder();
                List<Double>importesAnteriores =contrato.getImportesAlquiler();
                for (int i = 0; i < contrato.getImportesAlquiler().size(); i++) {
                    incrementosText.append(importesAnteriores.get(i));

                    if (i < importesAnteriores.size() - 1) {
                        incrementosText.append(">>>");
                    }
                }
                
                txtAAnt.setText(incrementosText.toString());
                if (contrato.isAlta()) {
                    lblMensaje.setText("¡¡¡ADVERTENCIA!!! Al confirmar el nuevo precio quedara en el registro permanentemente");
                    lblEditar.setVisible(true);

                } else {
                    lblMensaje.setText("No se puede realizar ninguna accion ya que el contrato no esta vigente");
                    lblEditar.setVisible(false);
                    rManual.setVisible(false);
                    rPorcentual.setVisible(false);
                    txtNuevoPrecio.setVisible(false);
                    sepNuevoPrecio.setVisible(false);
                    lblTabPrecio.setVisible(false);
                    lblImporteManual.setVisible(false);
                    lblPorc.setVisible(false);

                }

            } else {
                lblMensaje.setText("No se ha encontrado ningún contrato con ese ID en la base de datos");
                txtDireccion.setText("Inmueble");
            }
        } catch (NumberFormatException e) {
            lblMensaje.setText("El ID ingresado no es válido. Por favor, ingrese un número.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMouseClicked

    }//GEN-LAST:event_txtDireccionMouseClicked

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost

    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioMouseClicked

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtNuevoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPrecioActionPerformed

    private void txtNuevoPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevoPrecioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPrecioMouseClicked

    private void txtNuevoPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevoPrecioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoPrecioFocusLost

    private void rManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rManualActionPerformed
        actualizarUI();
    }//GEN-LAST:event_rManualActionPerformed

    private void rPorcentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPorcentualActionPerformed
        actualizarUI();
    }//GEN-LAST:event_rPorcentualActionPerformed

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        rManual.setVisible(true);
        rPorcentual.setVisible(true);
        txtNuevoPrecio.setVisible(true);
        sepNuevoPrecio.setVisible(true);
        lblTabPrecio.setVisible(true);
        actualizarUI();
    }//GEN-LAST:event_lblEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblImporteManual;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPorc;
    private javax.swing.JLabel lblTabPrecio;
    private javax.swing.JRadioButton rManual;
    private javax.swing.JRadioButton rPorcentual;
    private javax.swing.JSeparator sepDireccion;
    private javax.swing.JSeparator sepDireccion2;
    private javax.swing.JSeparator sepNombre1;
    private javax.swing.JSeparator sepNuevoPrecio;
    private javax.swing.JTextArea txtAAnt;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCont;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevoPrecio;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
