/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import models.Inmueble;
import servicios.Globales;
import static servicios.Globales.comportamientoTextField;
import servicios.InmuebleServicio;

/**
 *
 * @author Nelkha
 */
public class InmBajas extends javax.swing.JPanel {

    InmuebleServicio inmServ = new InmuebleServicio();
    Inmueble inmueble;

    public InmBajas() {
        initComponents();
        txtCalle.setEditable(false);
        txtAltura.setEditable(false);
        lblAlta.setVisible(false);
        lblBaja.setVisible(false);
        comportamientoTextField(txtIdInmueble, "ID INMUEBLE");
        Globales.activarBuscarConEnter(txtIdInmueble, btnBuscar);
        btnDarBaja.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        sepCalle = new javax.swing.JSeparator();
        sepAltura = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnDarBaja = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtIdInmueble = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        lblAlta = new javax.swing.JLabel();
        lblMensajeBajas = new javax.swing.JLabel();
        lblBaja = new javax.swing.JLabel();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sepCalle.setBackground(new java.awt.Color(255, 255, 255));
        sepCalle.setForeground(new java.awt.Color(0, 0, 0));
        sepCalle.setToolTipText("");
        sepCalle.setDoubleBuffered(true);
        sepCalle.setMinimumSize(new java.awt.Dimension(10, 10));
        sepCalle.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        sepAltura.setBackground(new java.awt.Color(255, 255, 255));
        sepAltura.setForeground(new java.awt.Color(0, 0, 0));
        add(sepAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 440, 20));

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCalle.setText("Calle");
        txtCalle.setBorder(null);
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCalleFocusLost(evt);
            }
        });
        txtCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCalleMouseClicked(evt);
            }
        });
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        txtAltura.setBackground(new java.awt.Color(255, 255, 255));
        txtAltura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAltura.setForeground(new java.awt.Color(102, 102, 102));
        txtAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAltura.setText("Altura");
        txtAltura.setBorder(null);
        txtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlturaFocusLost(evt);
            }
        });
        txtAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlturaMouseClicked(evt);
            }
        });
        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });
        add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        btnDarBaja.setBackground(new java.awt.Color(0, 51, 153));
        btnDarBaja.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnDarBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnDarBaja.setText("DAR DE BAJA");
        btnDarBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDarBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });
        add(btnDarBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE ID INMUEBLE PARA LA BAJA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtIdInmueble.setBackground(new java.awt.Color(255, 255, 255));
        txtIdInmueble.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdInmueble.setForeground(new java.awt.Color(102, 102, 102));
        txtIdInmueble.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdInmueble.setText("ID INMUEBLE");
        txtIdInmueble.setBorder(null);
        txtIdInmueble.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdInmuebleFocusLost(evt);
            }
        });
        txtIdInmueble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdInmuebleMouseClicked(evt);
            }
        });
        txtIdInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdInmuebleActionPerformed(evt);
            }
        });
        add(txtIdInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        lblAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/comprobado.png"))); // NOI18N
        add(lblAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        lblMensajeBajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblMensajeBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 290, 30));

        lblBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/cancelar.png"))); // NOI18N
        add(lblBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed
        inmueble.setAlta(false);
        lblMensajeBajas.setText("Ya no esta vigente");

        try {
            inmServ.editarInmueble(inmueble);
            lblAlta.setVisible(false);
            lblBaja.setVisible(true);
            lblMensaje.setText("El inmueble fue dado de baja correctamente");
            btnDarBaja.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(InmBajas.class.getName()).log(Level.SEVERE, null, ex);
            lblMensaje.setText("Algo fallo. El inmueble no fue dado de baja");

        }
    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void txtIdInmuebleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdInmuebleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInmuebleFocusLost

    private void txtIdInmuebleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdInmuebleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInmuebleMouseClicked

    private void txtIdInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdInmuebleActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            long idContrato = Long.parseLong(txtIdInmueble.getText());

            inmueble = inmServ.buscarInmuebleId(idContrato);

            if (inmueble != null) {
                String direccionC = inmueble.getDireccion();
                String[] partesDireccion = direccionC.split(" ");
                Pattern patronNumero = Pattern.compile("\\d");

                Matcher matcher = patronNumero.matcher(direccionC);

                if (matcher.find()) {

                    int posicionPrimerNumero = matcher.start();

                    String calle = direccionC.substring(0, posicionPrimerNumero).trim();
                    String altura = direccionC.substring(posicionPrimerNumero).trim();
                    txtCalle.setText(calle);
                    txtAltura.setText(altura);

                }

                if (inmueble.isAlta()) {
                    lblAlta.setVisible(true);
                    lblMensajeBajas.setText("El inmueble esta vigente.");
                    lblMensaje.setText("¡¡¡ADVERTENCIA!!! Al dar la baja no podra volver a su estado anterior");
                    btnDarBaja.setEnabled(true);
                } else {
                    lblBaja.setVisible(true);
                    lblMensajeBajas.setText("El contrato ya no esta vigente.");
                    lblMensaje.setText("No se puede realizar ninguna accion ya que el contrato no esta vigente");
                    

                }

            } else {
                lblMensaje.setText("No se ha encontrado ningún inmueble con ese ID en la base de datos");
                txtCalle.setText("Calle");
                txtAltura.setText("Altura");

            }
        } catch (NumberFormatException e) {
            lblMensaje.setText("El ID ingresado no es válido. Por favor, ingrese un número.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed

    }//GEN-LAST:event_txtAlturaActionPerformed

    private void txtAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlturaMouseClicked

    }//GEN-LAST:event_txtAlturaMouseClicked

    private void txtAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlturaFocusLost

    }//GEN-LAST:event_txtAlturaFocusLost

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMouseClicked

    }//GEN-LAST:event_txtCalleMouseClicked

    private void txtCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusLost

    }//GEN-LAST:event_txtCalleFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensajeBajas;
    private javax.swing.JSeparator sepAltura;
    private javax.swing.JSeparator sepCalle;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtIdInmueble;
    // End of variables declaration//GEN-END:variables
}
