/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static models.Contrato_.inquilino;
import models.Inmueble;
import servicios.Globales;
import static servicios.Globales.comportamientoTextField;
import servicios.InmuebleServicio;

/**
 *
 * @author Nelkha
 */
public class InmEditForm extends javax.swing.JPanel {

    InmuebleServicio inmServ = new InmuebleServicio();
    Inmueble inmueble;

    public InmEditForm() {
        initComponents();
        txtCalle.setEditable(false);
        txtAltura.setEditable(false);
        txtNuevaCalle.setEditable(false);
        txtNuevaAltura.setEditable(false);
        lblNuevaCalle.setVisible(false);
        txtNuevaCalle.setVisible(false);
        sepNuevaCalle.setVisible(false);
        lblNuevaAltura.setVisible(false);
        txtNuevaAltura.setVisible(false);
        sepNuevaAltura.setVisible(false);
        lblTabCalle.setVisible(false);
        lblTabAltura.setVisible(false);
        comportamientoTextField(txtIdImn, "ID");
        Globales.activarBuscarConEnter(txtIdImn, btnBuscar);
        btnEditarCalle.setVisible(false);
        btnEditarAltura.setVisible(false);
        btnConfirmar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        sepCalle = new javax.swing.JSeparator();
        sepAltura = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtIdImn = new javax.swing.JTextField();
        btnEditarCalle = new javax.swing.JLabel();
        btnEditarAltura = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        lblNuevaAltura = new javax.swing.JLabel();
        txtNuevaAltura = new javax.swing.JTextField();
        sepNuevaAltura = new javax.swing.JSeparator();
        lblNuevaCalle = new javax.swing.JLabel();
        txtNuevaCalle = new javax.swing.JTextField();
        sepNuevaCalle = new javax.swing.JSeparator();
        lblTabAltura = new javax.swing.JLabel();
        lblTabCalle = new javax.swing.JLabel();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sepCalle.setBackground(new java.awt.Color(255, 255, 255));
        sepCalle.setForeground(new java.awt.Color(0, 0, 0));
        sepCalle.setToolTipText("");
        sepCalle.setDoubleBuffered(true);
        sepCalle.setMinimumSize(new java.awt.Dimension(10, 10));
        sepCalle.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        sepAltura.setBackground(new java.awt.Color(255, 255, 255));
        sepAltura.setForeground(new java.awt.Color(0, 0, 0));
        add(sepAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 440, 20));

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCalle.setText("Calle");
        txtCalle.setBorder(null);
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCalleFocusLost(evt);
            }
        });
        txtCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCalleMouseClicked(evt);
            }
        });
        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        txtAltura.setBackground(new java.awt.Color(255, 255, 255));
        txtAltura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAltura.setForeground(new java.awt.Color(102, 102, 102));
        txtAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAltura.setText("Altura");
        txtAltura.setBorder(null);
        txtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlturaFocusLost(evt);
            }
        });
        txtAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlturaMouseClicked(evt);
            }
        });
        txtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaActionPerformed(evt);
            }
        });
        add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        btnConfirmar.setBackground(new java.awt.Color(0, 51, 153));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE INMUEBLE A EDITAR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtIdImn.setBackground(new java.awt.Color(255, 255, 255));
        txtIdImn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdImn.setForeground(new java.awt.Color(102, 102, 102));
        txtIdImn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdImn.setText("ID");
        txtIdImn.setBorder(null);
        txtIdImn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdImnFocusLost(evt);
            }
        });
        txtIdImn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdImnMouseClicked(evt);
            }
        });
        txtIdImn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdImnActionPerformed(evt);
            }
        });
        add(txtIdImn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        btnEditarCalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        btnEditarCalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCalleMouseClicked(evt);
            }
        });
        add(btnEditarCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        btnEditarAltura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        btnEditarAltura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarAlturaMouseClicked(evt);
            }
        });
        add(btnEditarAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        lblNuevaAltura.setText("Ingrese nueva altura");
        add(lblNuevaAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        txtNuevaAltura.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevaAltura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNuevaAltura.setForeground(new java.awt.Color(102, 102, 102));
        txtNuevaAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNuevaAltura.setBorder(null);
        txtNuevaAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevaAlturaFocusLost(evt);
            }
        });
        txtNuevaAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNuevaAlturaMouseClicked(evt);
            }
        });
        txtNuevaAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaAlturaActionPerformed(evt);
            }
        });
        add(txtNuevaAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 30));

        sepNuevaAltura.setBackground(new java.awt.Color(255, 255, 255));
        sepNuevaAltura.setForeground(new java.awt.Color(102, 204, 255));
        add(sepNuevaAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 20));

        lblNuevaCalle.setText("Ingrese nueva Calle");
        add(lblNuevaCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        txtNuevaCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevaCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNuevaCalle.setForeground(new java.awt.Color(102, 102, 102));
        txtNuevaCalle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNuevaCalle.setBorder(null);
        txtNuevaCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNuevaCalleFocusLost(evt);
            }
        });
        txtNuevaCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNuevaCalleMouseClicked(evt);
            }
        });
        txtNuevaCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaCalleActionPerformed(evt);
            }
        });
        add(txtNuevaCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 30));

        sepNuevaCalle.setBackground(new java.awt.Color(255, 255, 255));
        sepNuevaCalle.setForeground(new java.awt.Color(102, 204, 255));
        add(sepNuevaCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, 20));

        lblTabAltura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTabAltura.setForeground(new java.awt.Color(102, 204, 255));
        lblTabAltura.setText("TAB para confirmar");
        add(lblTabAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        lblTabCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTabCalle.setForeground(new java.awt.Color(102, 204, 255));
        lblTabCalle.setText("TAB para confirmar");
        add(lblTabCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed

    }//GEN-LAST:event_txtAlturaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (!inmueble.getDireccion().equalsIgnoreCase(txtCalle.getText() + " " + txtAltura.getText())) {
            inmueble.setDireccion(txtCalle.getText() + " " + txtAltura.getText());

        }

        try {
            inmServ.editarInmueble(inmueble);
            lblMensaje.setText("El inmueble fue modificado correctamente");
        } catch (Exception ex) {
            lblMensaje.setText("No se pudo modifcar el inmueble");
        }
        btnConfirmar.setEnabled(false);
        txtCalle.setText("Calle");
        txtAltura.setText("Altura");

        txtIdImn.setText("ID");

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCalleMouseClicked

    }//GEN-LAST:event_txtCalleMouseClicked

    private void txtCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusLost


    }//GEN-LAST:event_txtCalleFocusLost

    private void txtAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlturaMouseClicked

    }//GEN-LAST:event_txtAlturaMouseClicked

    private void txtAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlturaFocusLost

    }//GEN-LAST:event_txtAlturaFocusLost

    private void txtIdImnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdImnFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdImnFocusLost

    private void txtIdImnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdImnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdImnMouseClicked

    private void txtIdImnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdImnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdImnActionPerformed

    private void btnEditarCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCalleMouseClicked
        lblNuevaCalle.setVisible(true);
        txtNuevaCalle.setVisible(true);
        sepNuevaCalle.setVisible(true);
        lblTabCalle.setVisible(true);
        txtNuevaCalle.setEditable(true);
        txtNuevaCalle.requestFocus();


    }//GEN-LAST:event_btnEditarCalleMouseClicked

    private void btnEditarAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarAlturaMouseClicked
        lblNuevaAltura.setVisible(true);
        txtNuevaAltura.setVisible(true);
        sepNuevaAltura.setVisible(true);
        lblTabAltura.setVisible(true);
        txtNuevaAltura.setEditable(true);
        txtNuevaAltura.requestFocus();
    }//GEN-LAST:event_btnEditarAlturaMouseClicked

    private void txtNuevaAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevaAlturaFocusLost
        lblNuevaAltura.setVisible(false);
        txtNuevaAltura.setVisible(false);
        sepNuevaAltura.setVisible(false);
        lblTabAltura.setVisible(false);
        if (!txtNuevaAltura.getText().trim().isEmpty() && !txtNuevaAltura.getText().equalsIgnoreCase("Altura")) {
            txtAltura.setText(txtNuevaAltura.getText().toUpperCase());
            txtNuevaAltura.setText("");
            btnConfirmar.setEnabled(true);
        } else {
            txtNuevaAltura.setText("");
        }


    }//GEN-LAST:event_txtNuevaAlturaFocusLost

    private void txtNuevaAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevaAlturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaAlturaMouseClicked

    private void txtNuevaAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaAlturaActionPerformed

    private void txtNuevaCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNuevaCalleFocusLost
        lblNuevaCalle.setVisible(false);
        txtNuevaCalle.setVisible(false);
        sepNuevaCalle.setVisible(false);
        lblTabCalle.setVisible(false);
        if (!txtNuevaCalle.getText().trim().isEmpty() && !txtNuevaCalle.getText().equalsIgnoreCase("Nombre")) {
            txtCalle.setText(txtNuevaCalle.getText().toUpperCase());
            txtNuevaCalle.setText("");
            btnConfirmar.setEnabled(true);
        } else {
            txtNuevaCalle.setText("");
        }
    }//GEN-LAST:event_txtNuevaCalleFocusLost

    private void txtNuevaCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevaCalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaCalleMouseClicked

    private void txtNuevaCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaCalleActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        inmueble = inmServ.buscarInmuebleId(Long.parseLong(txtIdImn.getText().trim()));

        if (inmueble != null) {
            String direccionC = inmueble.getDireccion();
            String[] partesDireccion = direccionC.split(" ");
            Pattern patronNumero = Pattern.compile("\\d");

            Matcher matcher = patronNumero.matcher(direccionC);

            if (matcher.find()) {

                int posicionPrimerNumero = matcher.start();

                String calle = direccionC.substring(0, posicionPrimerNumero).trim();
                String altura = direccionC.substring(posicionPrimerNumero).trim();
                txtCalle.setText(calle);
                txtAltura.setText(altura);
                btnEditarCalle.setVisible(true);
                btnEditarAltura.setVisible(true);

            }
         
    }//GEN-LAST:event_btnBuscarMouseClicked
    else {
                lblMensaje.setText("No se ha encontrado ningun inmueble con ese ID en la base de datos");
                txtCalle.setText("Calle");
                txtAltura.setText("Altura");

            }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel btnEditarAltura;
    private javax.swing.JLabel btnEditarCalle;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNuevaAltura;
    private javax.swing.JLabel lblNuevaCalle;
    private javax.swing.JLabel lblTabAltura;
    private javax.swing.JLabel lblTabCalle;
    private javax.swing.JSeparator sepAltura;
    private javax.swing.JSeparator sepCalle;
    private javax.swing.JSeparator sepNuevaAltura;
    private javax.swing.JSeparator sepNuevaCalle;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtIdImn;
    private javax.swing.JTextField txtNuevaAltura;
    private javax.swing.JTextField txtNuevaCalle;
    // End of variables declaration//GEN-END:variables
}
