/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;
import models.Inmueble;
import static servicios.Globales.comportamientoTextField;
import static servicios.Globales.revertirComportamientoTextField;
import servicios.InmuebleServicio;

/**
 *
 * @author Nelkha
 */
public class InqEditForm extends javax.swing.JPanel {

    /**
     * Creates new form CrudForm2
     */
    public InqEditForm() {
        initComponents();
        txtNombre.setEditable(false);
        txtApellido.setEditable(false);
        txtTelefono.setEditable(false);
        
              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentIF = new javax.swing.JPanel();
        btnEditarTelefono = new javax.swing.JLabel();
        sepNombre = new javax.swing.JSeparator();
        sepApellido = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtCuit = new javax.swing.JTextField();
        sepTelefono = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        btnEditarNombre = new javax.swing.JLabel();
        btnEditarApellido = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();

        contentIF.setBackground(new java.awt.Color(255, 255, 255));

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        btnEditarTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarTelefonoMouseClicked(evt);
            }
        });
        add(btnEditarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        sepNombre.setBackground(new java.awt.Color(255, 255, 255));
        sepNombre.setForeground(new java.awt.Color(0, 0, 0));
        sepNombre.setToolTipText("");
        sepNombre.setDoubleBuffered(true);
        sepNombre.setMinimumSize(new java.awt.Dimension(10, 10));
        sepNombre.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 20));

        sepApellido.setBackground(new java.awt.Color(255, 255, 255));
        sepApellido.setForeground(new java.awt.Color(0, 0, 0));
        add(sepApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 20));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 440, 20));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setText(" Apellido");
        txtApellido.setBorder(null);
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        btnConfirmar.setBackground(new java.awt.Color(0, 51, 153));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 130, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGRESE CUIT INQUILINO A EDITAR");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");
        jSeparator11.setDoubleBuffered(true);
        jSeparator11.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator11.setPreferredSize(new java.awt.Dimension(10, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        txtCuit.setBackground(new java.awt.Color(255, 255, 255));
        txtCuit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCuit.setForeground(new java.awt.Color(102, 102, 102));
        txtCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuit.setText("CUIT");
        txtCuit.setBorder(null);
        txtCuit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuitFocusLost(evt);
            }
        });
        txtCuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCuitMouseClicked(evt);
            }
        });
        txtCuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuitActionPerformed(evt);
            }
        });
        add(txtCuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        sepTelefono.setBackground(new java.awt.Color(255, 255, 255));
        sepTelefono.setForeground(new java.awt.Color(0, 0, 0));
        sepTelefono.setToolTipText("");
        sepTelefono.setDoubleBuffered(true);
        sepTelefono.setMinimumSize(new java.awt.Dimension(10, 10));
        sepTelefono.setPreferredSize(new java.awt.Dimension(10, 10));
        add(sepTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 20));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setText("Telefono");
        txtTelefono.setBorder(null);
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        btnEditarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        btnEditarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarNombreMouseClicked(evt);
            }
        });
        add(btnEditarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        btnEditarApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/editar.png"))); // NOI18N
        btnEditarApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarApellidoMouseClicked(evt);
            }
        });
        add(btnEditarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/lupa.png"))); // NOI18N
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        lblTelefono.setText("< Presione para habilitar edicion del Telefono");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        lblNombre.setText("< Presione para habilitar edicion del nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        lblApellido.setText("< Presione para habilitar edicion del Apellido");
        add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
     
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        txtNombre.setEditable(false);
        sepNombre.setForeground(Color.black);
        revertirComportamientoTextField(txtNombre,"Nombre");
               
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
      txtNombre.setEditable(false);
        sepNombre.setForeground(Color.black);
        revertirComportamientoTextField(txtApellido,"Apellido");  
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtCuitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuitFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitFocusLost

    private void txtCuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCuitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitMouseClicked

    private void txtCuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitActionPerformed

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        txtNombre.setEditable(false);
        sepNombre.setForeground(Color.black);
        revertirComportamientoTextField(txtTelefono,"Telefono"); 
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnEditarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarNombreMouseClicked
        comportamientoTextField(txtNombre,"Nombre");
        txtNombre.setEditable(true);
        sepNombre.setForeground(Color.green);
    }//GEN-LAST:event_btnEditarNombreMouseClicked

    private void btnEditarApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarApellidoMouseClicked
       comportamientoTextField(txtApellido,"Apellido");
        txtNombre.setEditable(true);
        sepNombre.setForeground(Color.green);  
    }//GEN-LAST:event_btnEditarApellidoMouseClicked

    private void btnEditarTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarTelefonoMouseClicked
       comportamientoTextField(txtApellido,"Telefono");
        txtNombre.setEditable(true);
        sepNombre.setForeground(Color.green);  
    }//GEN-LAST:event_btnEditarTelefonoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel btnEditarApellido;
    private javax.swing.JLabel btnEditarNombre;
    private javax.swing.JLabel btnEditarTelefono;
    private javax.swing.JPanel contentIF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JSeparator sepApellido;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JSeparator sepTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
