/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import models.Inquilino;
import servicios.InquilinoServicio;

/**
 *
 * @author Nelkha
 */
public class InqList extends javax.swing.JPanel {

    InquilinoServicio inqServ = new InquilinoServicio();
    DefaultTableModel dtm = new DefaultTableModel();
    List<Inquilino> inquilinos = inqServ.consultaTodos();

    private void actualizarTabla() {
        String filtroNombre = txtFiltro.getText().toUpperCase().trim();

        dtm.setRowCount(0);

        for (Inquilino inq : inquilinos) {
            String nombreCompleto = inq.getNombre() + " " + inq.getApellido();
            nombreCompleto = nombreCompleto.toUpperCase().trim();

            boolean cumpleFiltroNombre = filtroNombre.isEmpty() || !filtroNombre.equals("FILTRAR POR NOMBRE");
            if (cumpleFiltroNombre) {

                if (nombreCompleto.contains(filtroNombre)) {
                    dtm.addRow(new Object[]{inq.getId(), inq.getCuit(), nombreCompleto, inq.getTelefono()});
                }

            } else {

                dtm.addRow(new Object[]{inq.getId(), inq.getCuit(), nombreCompleto, inq.getTelefono()});

            }

        }
    }

    public InqList() {
        initComponents();
        txtFiltro.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarTabla();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarTabla();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarTabla();
            }
        });
        String[] titulos = new String[]{"ID", "CUIT", "INQ.", "TEL"};
        dtm.setColumnIdentifiers(titulos);

        tblCont.setModel(dtm);
        tblCont.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblCont.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblCont.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblCont.getColumnModel().getColumn(3).setPreferredWidth(60);

        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCont = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPI.setBackground(new java.awt.Color(255, 255, 255));
        contentPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO INQUILINOS");
        contentPI.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        tblCont.setBackground(new java.awt.Color(255, 255, 255));
        tblCont.setForeground(new java.awt.Color(0, 0, 0));
        tblCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCont);

        contentPI.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 390));

        txtFiltro.setText("Filtrar por nombre");
        contentPI.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 20));

        add(contentPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCont;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
