/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Contrato;
import models.Inquilino;
import servicios.ContratoServicio;
import servicios.InquilinoServicio;

/**
 *
 * @author Nelkha
 */
public class InqPage extends javax.swing.JPanel {

    InquilinoServicio inqServ = new InquilinoServicio();

    public InqPage(String cuit) {
        initComponents();
        Inquilino inquilino = inqServ.buscarInquilinoPorCuit(cuit);
        List<Contrato> contratos = inqServ.buscarContratosInquilino(inquilino);
        lblInqTitle.setText(inquilino.getNombre() + " " + inquilino.getApellido());
        StringBuilder contratoText = new StringBuilder();

        for (Contrato contrato : contratos) {
            contratoText.append(contrato.getId()).append("\n")
                    .append(contrato.getInquilino().getNombre()).append("\n")
                    .append(contrato.getInmueble().getDireccion()).append("\n")
                    .append(contrato.getMontoAlquiler())
                    .append(contrato.getImportesAlquiler().get(0))
                    .append("\n"); // Agregar un espacio entre contratos
        }

        txaCont.setText(contratoText.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPI = new javax.swing.JPanel();
        lblInqTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCont = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPI.setBackground(new java.awt.Color(255, 255, 255));
        contentPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInqTitle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblInqTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblInqTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contentPI.add(lblInqTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        txaCont.setColumns(20);
        txaCont.setRows(5);
        jScrollPane1.setViewportView(txaCont);

        contentPI.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, -1));

        add(contentPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInqTitle;
    private javax.swing.JTextArea txaCont;
    // End of variables declaration//GEN-END:variables
}
