/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Contrato;
import models.Inquilino;
import servicios.ContratoServicio;
import servicios.InquilinoServicio;

/**
 *
 * @author Nelkha
 */
public class InqPage extends javax.swing.JPanel {

    InquilinoServicio inqServ = new InquilinoServicio();
    DefaultTableModel dtm = new DefaultTableModel();

    public InqPage(String cuit) {
        initComponents();
        String[] titulos = new String[]{"ID", "INM", "I.ACTUAL", "F. INCIO", "F.FIN"};
        dtm.setColumnIdentifiers(titulos);

        tblContInq.setModel(dtm);
        tblContInq.getColumnModel().getColumn(0).setPreferredWidth(5); // ID
        tblContInq.getColumnModel().getColumn(1).setPreferredWidth(125); // DIRECCION
        tblContInq.getColumnModel().getColumn(2).setPreferredWidth(55);
        tblContInq.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblContInq.getColumnModel().getColumn(4).setPreferredWidth(50);
       
        // Formatear el BigDecimal
        DecimalFormat formato = new DecimalFormat("#,##0.00");
        Inquilino inquilino = inqServ.buscarInquilinoPorCuit(cuit);
        List<Contrato> contratos = inqServ.buscarContratosInquilino(inquilino);
        lblInqTitle.setText(inquilino.getNombre() + " " + inquilino.getApellido());
        for (Contrato cont : contratos) {
            dtm.addRow(new Object[]{cont.getId(), cont.getInmueble().getDireccion(),
            "$ "+formato.format(BigDecimal.valueOf(cont.getMontoAlquiler())),cont.getFechaInicio(),cont.getFechaFin()});
        }
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPI = new javax.swing.JPanel();
        lblInqTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContInq = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(490, 480));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(490, 480));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPI.setBackground(new java.awt.Color(255, 255, 255));
        contentPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInqTitle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblInqTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblInqTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contentPI.add(lblInqTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        tblContInq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblContInq);

        contentPI.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 400));

        add(contentPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPI;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInqTitle;
    private javax.swing.JTable tblContInq;
    // End of variables declaration//GEN-END:variables
}
